In [ ]:
import numpy as np

In [ ]:
# 1
a = np.arange(30).reshape(15,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [ ]:
# 2
a = np.random.randint(0,101,60).reshape(5,2,6)
print(a.ndim,a.shape)

3 (5, 2, 6)


In [ ]:
# 3
a = np.random.randint(0,10,(2,10)).reshape(-1)
a

array([6, 9, 4, 5, 1, 0, 3, 7, 5, 0, 8, 8, 5, 9, 9, 4, 1, 3, 4, 5])

In [ ]:
# 4
a = np.random.randint(0,101,(2,5))
for i in a: #Yavaş
  for x in i:
    print(x)

93
79
14
17
19
23
42
73
91
54


In [ ]:
for i in np.nditer(a):
  print(i)

93
79
14
17
19
23
42
73
91
54


In [ ]:
# 5
a = np.array([5,10,15,20,25,30])
b = np.array([1,2,3,4,5,6])
print(a+b,a-b,a*b,a/b)

[ 6 12 18 24 30 36] [ 4  8 12 16 20 24] [  5  20  45  80 125 180] [5. 5. 5. 5. 5. 5.]


In [ ]:
# 6
a = np.random.randint(0,100,10)
print(sum(a),a.mean(),max(a),a.var(),a.std())

416 41.6 96 1255.2399999999998 35.429366350529044


In [ ]:
# 7
a = np.arange(0,20)
b = np.arange(500,531)
np.concatenate((a,b))

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

In [ ]:
# 8
a = np.arange(15,51)
b = np.arange(10,101)
c = np.concatenate((a,b))
c[25:51] = 888
c

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
# 9
a = np.arange(0,40).reshape(8,5)
b = np.arange(320,360).reshape(8,5)
ax1= np.concatenate((a,b),1)
ax0 = np.concatenate((a,b),0)
print(ax1,ax0,sep="\n\n\n\n")

[[  0   1   2   3   4 320 321 322 323 324]
 [  5   6   7   8   9 325 326 327 328 329]
 [ 10  11  12  13  14 330 331 332 333 334]
 [ 15  16  17  18  19 335 336 337 338 339]
 [ 20  21  22  23  24 340 341 342 343 344]
 [ 25  26  27  28  29 345 346 347 348 349]
 [ 30  31  32  33  34 350 351 352 353 354]
 [ 35  36  37  38  39 355 356 357 358 359]]



[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]


In [ ]:
# 10
# ax2 = np.concatenate((a,b),2) hata veriyor
ax2s = np.stack((a,b),axis = 2)
ax2s

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

In [ ]:
# 11
a = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(a==5)

(array([ 5, 13]),)

In [ ]:
# 12
np.where(a%2==0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

In [ ]:
# 13
np.where(a>4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

In [ ]:
# 14
np.where(a%5==0)

(array([ 1,  2,  5, 13]),)

In [ ]:
# 15
a = np.random.randint(85,101)
a

100

In [ ]:
# 16
a = np.random.randint(10,100,(3,3))
a

array([[88, 97, 10],
       [38, 70, 80],
       [70, 57, 65]])

In [ ]:
# 17
a = np.arange(36,60)
b = np.random.choice(a)
b

37

In [ ]:
# 18
a = np.array([3,8,10,53])
b = np.random.choice(a,(2,5))
b

array([[53,  3,  3,  8, 10],
       [10,  3, 53, 10, 53]])