In [ ]:
import numpy as np

In [ ]:
# 1
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a.ndim

3

In [ ]:
# 2
a = np.arange(34,113,6)
a

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [ ]:
# 3
a = np.linspace(50,500,91, dtype = int)
a

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

In [ ]:
# 4
a = np.logspace(2,4,8)
a

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

In [ ]:
# 5
a = np.arange(9).reshape(3,-1)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 6
a = np.zeros((6,6),int)
a

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
# 7
a = np.ones((4,4),int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# 8
a = np.eye(8,dtype=int)
a

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [ ]:
# 9
a = np.identity(5,int)*3
a

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [ ]:
# 10
a = np.random.rand(6)
a

array([0.61460582, 0.57481834, 0.78102243, 0.84337424, 0.02846861,
       0.65105881])

In [ ]:
# 11
a = np.random.randint(50,101,(5,2))
a

array([[ 97,  93],
       [ 52, 100],
       [ 72,  85],
       [ 75,  93],
       [ 58,  79]])

In [ ]:
# 12
a = np.random.randint(100,1000,(2,5,5))
print(a.ndim,a.shape)

3 (2, 5, 5)


In [ ]:
# 13
a = np.random.randint(0,101,10)
print(a.max(),a.argmax(),a.min(),a.argmin())

97 1 0 2


In [ ]:
# 14
a = np.random.randint(300,501,(2,2,5))

In [ ]:
a

array([[[424, 344, 450, 497, 380],
        [468, 331, 449, 384, 484]],

       [[377, 430, 495, 392, 399],
        [369, 360, 362, 323, 424]]])

In [ ]:
print(f"Max : {a[0][0][3]} \nMin : {a[1][1][3]}")

Max : 497 
Min : 323


In [ ]:
# 15
a = np.arange(0,51)
a[21:35] = 500
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])

In [ ]:
# done